sudo: required
language: ruby c

os:
  - osx
  - linux

rvm:
  - "2.1"
  - "2.5"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pip2 install gcovr && brew tap osx-cross/avr; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then travis_wait 30 brew install avr-gcc; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo pip install gcovr; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq && sudo apt-get install --assume-yes --quiet gcc-multilib && sudo apt-get install -qq gcc-avr binutils-avr avr-libc; fi

install:
  - gem update bundler
  - bundle install

script:
  - bundle exec rake ci
