---

version: "{build}"

install:
  - set PATH=C:\Ruby%ruby_version%\bin;C:\MinGW\bin;%PATH%
  - gem update --system --no-document
  - gem install bundler --no-document
  - bundle install --jobs 3 --retry 3

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - git submodule update --init --recursive

test_script:
  - bundle exec rake ci

environment:
  matrix:
    - ruby_version: '21'
    - ruby_version: 21-x64
    - ruby_version: '24'
    - ruby_version: 24-x64
